### ISSUE TITLE
Reconfigure Joystick Ports

### ISSUE THREAD

**Issue by manojkr19** [FRC2495/FRC-2495-2018#1]
Joystick Moves [initial proposal for NEW joystick]

Right Stick - Main
-------------------
Move Forward  - Fwd
Move Backward - Rev
Rotate Left   - Left
Rotate Right  - Right

Jackup  - 3 or 4
Jackdown- 3 or 4

Abort Closed Loop - 5 or 6

Slide Left - Left
Slide Right - Right

Cube Grab  -  GP A
Cube Spit  -  GP B

Elevator Scale - GP Up
Elevator Switch - GP Left/Right 
Elevator Down - GP Down
Elevator control - GP Left Joystick

Hinge Up - GP X
Hinge Down - GP Y
Hinge control - GP Right Joystick

Climb - GP Left Button + 1

Left Stick
---------
Special functions like move distance, rotate90deg etc...
Align to Cube
Move to Cube 

1 - 
2
3 - move 50
4 - turn -90 deg
5 - turn 90 dev
6 - reset encoders
7
8 - Align to Cube
9 - Move to Cube
10 - Elevator Home

**Comment by manojkr19** [comment]
Old Joystick [as in Current ATTACK 3 joysticks]

Right Joystick & Gamepad
-------------------------
Move Forward - Fwd
Move Backward - Rev
Rotate Left - Left
Rotate Right - Right

Jackup/Jackdown - Button 2 

Abort Closed Loop - 7
Reset Encoders - 6

Slide Left - Left
Slide Right - Right

Cube Grab - GP A
Cube Spit - GP B

Elevator Home - Back
Elevator Scale/Down - Left button
Elevator Switch - GP left bumper
*Elevator control - GP Left Joystick

Hinge Home - Start
Hinge Up/Down - GP X
Hinge MidWay - GP Y
*Hinge control - GP Right Joystick

*Climb - GP Right Button + Joystick Button 1

Turn to Cube - Button 4
Move to Cube - Button 5

**Comment by gartaud** [comment]
![leftjoystickbuttonmapversion2](https://user-images.githubusercontent.com/17017607/36623049-79f4ec3c-18cf-11e8-8e97-8eff458e88da.png)

**Comment by gartaud** [comment]
![rightjoystickbuttonmapversion2](https://user-images.githubusercontent.com/17017607/36623054-8a88f142-18cf-11e8-9ffc-03b9d7709d74.png)

**Comment by gartaud** [comment]
![gamepadbuttonmapversion 2](https://user-images.githubusercontent.com/17017607/36623078-a85405ea-18cf-11e8-890f-19e68af45e70.png)

**Comment by gartaud** [comment]
I assume that everybody is happy with the latest button assignments. Feel free to reopen to propose changes.

**Comment by gartaud** [comment]
![rightjoystickbuttonmapversion4](https://user-images.githubusercontent.com/17017607/36709443-e5c734d8-1b45-11e8-9e44-3e27872db24b.png)

**Comment by gartaud** [comment]
Now that we can access the triggers and four distinct positions per stick on the gamepad we may want to revisit the button assignments and get rid of the toggles for the elevator and the hinge.

**Comment by gartaud** [comment]
![leftjoystickbuttonmapversion3](https://user-images.githubusercontent.com/17017607/36826510-d04f367c-1cdb-11e8-8af5-bf26ddfff59a.png)

**Comment by gartaud** [comment]
![rightjoystickbuttonmapversion5](https://user-images.githubusercontent.com/17017607/36826518-dc275d9e-1cdb-11e8-8be0-e6ee0ec06ce2.png)

**Comment by gartaud** [comment]
![buttonmap gamepad version4](https://user-images.githubusercontent.com/17017607/36826523-e4b72188-1cdb-11e8-8d54-85250f5a2d3d.png)

**Comment by gartaud** [comment]
![rightjoystickbuttonmapversion6](https://user-images.githubusercontent.com/17017607/37074553-6c11c052-219b-11e8-8be7-0e5f5bb384e5.png)

**Comment by gartaud** [comment]
No complaint regarding button layout. Suggesting we close this issue.
