### ISSUE TITLE
Upgrade software

### ISSUE THREAD

**Issue by manojkr19** [FRC2495/FRC-2495-2018#12]
Install the latest WPI lib on the laptop (by checking for updates in Eclipse)
Install the latest Phoenix framework on the laptop (by downloading directly from CTRE's website)

**Comment by gartaud** [comment]
WPI lib should be upgraded to 2018.3.3 using Eclipse's "Help, Check for Updates" feature  (https://github.com/wpilibsuite/allwpilib/releases/tag/v2018.3.3)

Phoenix framework should be upgraded to at least Phoenix 5.2.2.0 to get rid of the sporadic error -63194 as described at https://github.com/CrossTheRoadElec/Phoenix-Documentation#driver-station-system-watchdog--63194-and-motor-controllers-not-enabling.
Installer for Phoenix 5.2.2.0 can be found at http://www.ctr-electronics.com/control-system/hro.html#product_tabs_technical_resources

**Comment by gartaud** [comment]
WPI lib and Phoenix framework were upgraded to the latest versions available as of 04-MAR-208 (WPI lib 2018.3.3 and Phoenix 5.3.1).

**Comment by gartaud** [comment]
Closing. Overtaken by events.
