### ISSUE TITLE
Tune PID

### ISSUE THREAD

**Issue by manojkr19** [FRC2495/FRC-2495-2018#7]
Check that "turn" PID controller of the large drivetrain is properly tuned so that we can turn by large angles (e.g. 90 degrees) without oscillating and that we can turn by small angles (e.g. 5 degrees) without getting stuck. Do that on carpet.

**Comment by gartaud** [comment]
Turn PID controller on practice bot is pretty well tuned on carpet. Competition bot tuned on wood floor, and somehow requires much more power. May require further tuning on carpet (i.e. MIN_TURN_PCT_OUTPUT and MAX_TURN_PCT_OUTPUT in Drivetrain.java might need to be increased a tad further when Robot.COMPETITION_BOT_CONFIG is true).

**Comment by gartaud** [comment]
Good enough. Closing.
