### ISSUE TITLE
Calibrate mini drivetrain

### ISSUE THREAD

**Issue by manojkr19** [FRC2495/FRC-2495-2018#8]
Check that mini drivretrain is properly calibrated so that we can accurately move athwart by given distance using position mode of motor controllers.

**Comment by gartaud** [comment]
Mini drivetrain is properly calibrated on practice bot. Check competition bot prior to competition.

**Comment by gartaud** [comment]
Encoders on mini drivetrain of competition bot are mounted differently, and therefore use different ratio. ENCODER_MULTIPLIER constant sets accordingly in MiniDrivetrain.java based on Robot.COMPETITION_BOT_CONFIG setting. Closing.
